/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package capaCliente;

import capaLogica.clsUsuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class jdManPass extends javax.swing.JDialog {

    clsUsuario objUsu = new clsUsuario();

    /**
     * Creates new form jdManPass
     */
    public jdManPass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Menú - Mantenimiento Contraseña");
    }

    private void listarUsuarios() throws SQLException, Exception {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };;
        modelo.addColumn("Código");
        modelo.addColumn("País");
        modelo.addColumn("Doc");
        modelo.addColumn("N° Documento");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Sexo");
        modelo.addColumn("Fecha Nac");
        modelo.addColumn("Dirección");
        modelo.addColumn("Celular");
        modelo.addColumn("Correo");
        modelo.addColumn("Cargo");
        modelo.addColumn("User");
        modelo.addColumn("Estado");
        modelo.addColumn("Sede");

        ResultSet rsUsu = objUsu.listarUsuarios();

        while (rsUsu.next()) {
            String sexo = "";
            if (rsUsu.getBoolean("sexo")) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            Vector registro = new Vector();
            registro.add(0, rsUsu.getString("codigo"));
            registro.add(1, rsUsu.getString("pais"));
            registro.add(2, rsUsu.getString("tipo_doc"));
            registro.add(3, rsUsu.getString("numero_documento"));
            registro.add(4, rsUsu.getString("nombre_completo"));
            registro.add(5, sexo);
            registro.add(6, rsUsu.getString("f_nacimiento"));
            registro.add(7, rsUsu.getString("direccion"));
            registro.add(8, rsUsu.getString("telefono"));
            registro.add(9, rsUsu.getString("correo"));
            registro.add(10, rsUsu.getString("cargo"));
            registro.add(11, rsUsu.getString("usuario"));
            registro.add(12, rsUsu.getString("estado"));
            registro.add(13, rsUsu.getString("sede"));
            modelo.addRow(registro);
        }

        tblDatos.setModel(modelo);
        tblDatos.getColumnModel().getColumn(0).setPreferredWidth(28);
        tblDatos.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblDatos.getColumnModel().getColumn(2).setPreferredWidth(10);
        tblDatos.getColumnModel().getColumn(5).setPreferredWidth(37);
        tblDatos.getColumnModel().getColumn(6).setPreferredWidth(40);
        tblDatos.getColumnModel().getColumn(8).setPreferredWidth(37);
        tblDatos.getColumnModel().getColumn(10).setPreferredWidth(21);
        tblDatos.getColumnModel().getColumn(11).setPreferredWidth(15);
        tblDatos.getColumnModel().getColumn(12).setPreferredWidth(10);
        tblDatos.getColumnModel().getColumn(13).setPreferredWidth(35);
        tblDatos.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtP = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnModificar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 182, 139));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(113, 49, 18));
        jLabel14.setText("Contraseña:");

        txtP.setBackground(new java.awt.Color(245, 224, 206));
        txtP.setForeground(new java.awt.Color(113, 49, 18));
        txtP.setText("jPasswordField1");

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(113, 49, 18));
        jLabel18.setText("Confirmar Contraseña:");

        txtP1.setBackground(new java.awt.Color(245, 224, 206));
        txtP1.setForeground(new java.awt.Color(113, 49, 18));
        txtP1.setText("jPasswordField1");

        tblDatos.setBackground(new java.awt.Color(245, 224, 206));
        tblDatos.setForeground(new java.awt.Color(113, 49, 18));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        btnModificar1.setBackground(new java.awt.Color(113, 49, 18));
        btnModificar1.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(245, 224, 206));
        btnModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/editar_32px.png"))); // NOI18N
        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar1)
                .addGap(303, 303, 303))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDatosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            listarUsuarios();
        } catch (Exception ex) {
            Logger.getLogger(jdManPass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
        try {
            if (tblDatos.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario a modificar!");
            } else {
                int cod = Integer.parseInt(tblDatos.getValueAt(tblDatos.getSelectedRow(), 0).toString());
                if (!txtP.getText().isBlank() && !txtP1.getText().isBlank()) {
                    int opc = JOptionPane.showConfirmDialog(null, "¿Está seguro en modificar la contraseña de este usuario?", "Mensaje de Sistema", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if (opc == 0) {
                        int i = objUsu.modificarPass(cod, txtP.getText(), txtP1.getText());
                        if (i == 0) {
                            JOptionPane.showMessageDialog(null, "Contraseña modificada correctamente");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Mensaje de sistema", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar contraseña: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JPasswordField txtP;
    private javax.swing.JPasswordField txtP1;
    // End of variables declaration//GEN-END:variables
}
