/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package capaCliente;

import capaLogica.clsEjemplar;
import capaLogica.clsSede;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class jdManEjemplar extends javax.swing.JDialog {

    clsSede objSede = new clsSede();
    clsEjemplar objEjemplar = new clsEjemplar();

    public jdManEjemplar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void listarComboSede() {
        ResultSet rs = null;
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        cboSede.setModel(modelo);

        try {
            rs = objSede.listarSede();
            while (rs.next()) {
                modelo.addElement(rs.getString("nombre"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar el combo Sede --->" + e.getMessage());
        }
    }

    public void listarEjemplaresSede() {
        ResultSet rsEjem = null;
        String asignacion = "";
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Cantidad");
        modelo.addColumn("Libro");
        modelo.addColumn("Sede");
        tblEjemplaresSede.setModel(modelo);

        try {
            rsEjem = objEjemplar.listarEjemplaresSede();
            while (rsEjem.next()) {
                if (!rsEjem.getString("nombre_sede").equals("S")) {
                    asignacion = "Sin Asignar";
                } else {
                    asignacion = rsEjem.getString("nombre_sede");
                }
                modelo.addRow(new Object[]{
                    rsEjem.getString("cantidad_ejemplares"),
                    rsEjem.getString("nombre_libro"),
                    rsEjem.getString("nombre_sede")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar Ejemplares por sede --->" + e.getMessage());
        }
    }

    public void listarEjemplaresSedeIndiv() {
        ResultSet rsEjem = null;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Libro");
        modelo.addColumn("Sede");
        tblEjemplaresSede.setModel(modelo);

        try {
            rsEjem = objEjemplar.listarEjemplarSedeIndiv();
            while (rsEjem.next()) {
                modelo.addRow(new Object[]{
                    rsEjem.getString("codigo"),
                    rsEjem.getString("libro"),
                    rsEjem.getString("sede")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar Ejemplares por sede --->" + e.getMessage());
        }
    }

    public void listarEjemplaresDisponibles() {
        ResultSet rsEjem = null;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Dispoible");
        modelo.addColumn("Libro");
        tblEjemplaresSede.setModel(modelo);

        try {
            rsEjem = objEjemplar.listarEjemplaresSinA();
            while (rsEjem.next()) {
                modelo.addRow(new Object[]{
                    rsEjem.getString("disponible"),
                    rsEjem.getString("libro")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar Ejemplares por sede --->" + e.getMessage());
        }
    }

    public void limpiar() {
        txtCodigo.setText("");
        txtNombreLibro.setText("");
        spnCantidad.setValue(0);
        cboSede.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFindLibro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjemplaresSede = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNombreLibro = new javax.swing.JTextArea();
        cboSede = new javax.swing.JComboBox<>();
        spnCantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnFindCodigo = new javax.swing.JButton();
        chkSinSede = new javax.swing.JCheckBox();
        chkIndividual = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Ejemplar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 182, 139));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(113, 49, 18));
        jLabel2.setText("Libro:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(113, 49, 18));
        jLabel3.setText("Sede:");

        btnFindLibro.setBackground(new java.awt.Color(113, 49, 18));
        btnFindLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar_24px.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(113, 49, 18));
        jSeparator1.setForeground(new java.awt.Color(113, 49, 18));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblEjemplaresSede.setBackground(new java.awt.Color(245, 224, 206));
        tblEjemplaresSede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEjemplaresSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjemplaresSedeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEjemplaresSede);

        jSeparator2.setBackground(new java.awt.Color(113, 49, 18));
        jSeparator2.setForeground(new java.awt.Color(113, 49, 18));

        txtNombreLibro.setEditable(false);
        txtNombreLibro.setBackground(new java.awt.Color(245, 224, 206));
        txtNombreLibro.setColumns(20);
        txtNombreLibro.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        txtNombreLibro.setForeground(new java.awt.Color(113, 49, 18));
        txtNombreLibro.setLineWrap(true);
        txtNombreLibro.setRows(5);
        txtNombreLibro.setWrapStyleWord(true);
        txtNombreLibro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(txtNombreLibro);

        cboSede.setBackground(new java.awt.Color(245, 224, 206));
        cboSede.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        cboSede.setForeground(new java.awt.Color(113, 49, 18));
        cboSede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(113, 49, 18));
        jLabel5.setText("Cantidad:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(113, 49, 18));
        jLabel4.setText("Código:");

        txtCodigo.setBackground(new java.awt.Color(245, 224, 206));
        txtCodigo.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(113, 49, 18));
        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFindCodigo.setBackground(new java.awt.Color(113, 49, 18));
        btnFindCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar_24px.png"))); // NOI18N
        btnFindCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCodigoActionPerformed(evt);
            }
        });

        chkSinSede.setBackground(new java.awt.Color(230, 182, 139));
        chkSinSede.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        chkSinSede.setForeground(new java.awt.Color(113, 49, 18));
        chkSinSede.setText("Sin Asignar");
        chkSinSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkSinSedeMouseClicked(evt);
            }
        });

        chkIndividual.setBackground(new java.awt.Color(230, 182, 139));
        chkIndividual.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        chkIndividual.setForeground(new java.awt.Color(113, 49, 18));
        chkIndividual.setText("Individual");
        chkIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkIndividualMouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(113, 49, 18));
        jButton7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(245, 224, 206));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nuevo_32px.png"))); // NOI18N
        jButton7.setText("NUEVO");

        jButton12.setBackground(new java.awt.Color(113, 49, 18));
        jButton12.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(245, 224, 206));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/editar_32px.png"))); // NOI18N
        jButton12.setText("Modificar");

        btnSalir.setBackground(new java.awt.Color(113, 49, 18));
        btnSalir.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(245, 224, 206));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir_32px.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(113, 49, 18));
        jButton8.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(245, 224, 206));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar_32px.png"))); // NOI18N
        jButton8.setText("Eliminar");

        jButton9.setBackground(new java.awt.Color(113, 49, 18));
        jButton9.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(245, 224, 206));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/darBaja_32px.png"))); // NOI18N
        jButton9.setText("Dar Baja");

        btnLimpiar.setBackground(new java.awt.Color(113, 49, 18));
        btnLimpiar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(245, 224, 206));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar_32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(107, 39));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(107, 39));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(107, 39));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton7))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSede, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                            .addComponent(txtCodigo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnFindCodigo)
                                            .addComponent(btnFindLibro))))
                                .addGap(0, 75, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(109, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkSinSede)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFindCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSede, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkSinSede)
                                .addComponent(chkIndividual))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void chkSinSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSinSedeMouseClicked
        if (chkSinSede.isSelected()) {
            listarEjemplaresDisponibles();
        } else {
            listarEjemplaresSede();
        }
    }//GEN-LAST:event_chkSinSedeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listarComboSede();
        listarEjemplaresSede();
    }//GEN-LAST:event_formWindowOpened

    private void tblEjemplaresSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjemplaresSedeMouseClicked
        if (chkIndividual.isSelected()) {
            txtCodigo.setText(String.valueOf(tblEjemplaresSede.getValueAt(tblEjemplaresSede.getSelectedRow(), 0)));
        } else {
            int columCount = tblEjemplaresSede.getColumnCount();

            String libro = (String) (tblEjemplaresSede.getValueAt(tblEjemplaresSede.getSelectedRow(), 1));

            String sede = null;
            if (columCount > 2) {
                sede = (String) (tblEjemplaresSede.getValueAt(tblEjemplaresSede.getSelectedRow(), 2));
            }
            
            ResultSet rsCodigos = null;
            try {
                if(sede!=null){
                    rsCodigos = objEjemplar.obtenerCodigoEjemplar(libro, sede);
                }else{
                    rsCodigos = objEjemplar.obtenerCodigoEjemplar(libro);
                }
                
                StringBuilder codigosConcatenados = new StringBuilder();
                while (rsCodigos.next()){
                    if (codigosConcatenados.length() > 0) {
                        codigosConcatenados.append(", ");
                    }
                    codigosConcatenados.append(rsCodigos.getInt("codigo"));
                }
                rsCodigos.close();
                txtCodigo.setText(codigosConcatenados.toString());
            } catch (Exception e) {
                
            }   
        }
        
        btnFindCodigoActionPerformed(null);
    }//GEN-LAST:event_tblEjemplaresSedeMouseClicked

    private void btnFindCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCodigoActionPerformed
        ResultSet rsCodigo = null;
        try {
            if (txtCodigo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe ingresar uno o más códigos para buscar");
            } else {
                String[] codigosTexto = txtCodigo.getText().split(",");
                int[] codigos;

                codigos = new int[codigosTexto.length];
                for (int i = 0; i < codigosTexto.length; i++) {
                    codigos[i] = Integer.parseInt(codigosTexto[i].trim());
                }

                rsCodigo = objEjemplar.buscarPorCodigo(codigos);

                if (rsCodigo != null && rsCodigo.next()) {
                    txtNombreLibro.setText(rsCodigo.getString("nombre_libro"));
                    spnCantidad.setValue(rsCodigo.getObject("cantidad"));
                    if (chkSinSede.isSelected()) {
                        cboSede.setSelectedIndex(0);
                    } else {
                        cboSede.setSelectedItem(rsCodigo.getString("nombre_sede"));
                    }
                    rsCodigo.close();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontraron resultados para los códigos ingresados.");
                    limpiar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnFindCodigoActionPerformed

    private void chkIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkIndividualMouseClicked
        if (chkIndividual.isSelected()) {
            listarEjemplaresSedeIndiv();
        } else {
            listarEjemplaresSede();
        }
    }//GEN-LAST:event_chkIndividualMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindCodigo;
    private javax.swing.JButton btnFindLibro;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboSede;
    private javax.swing.JCheckBox chkIndividual;
    private javax.swing.JCheckBox chkSinSede;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblEjemplaresSede;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
